# need Redis + Mongodb + containerize source + bot
version: "3.9"
services:
  redis:
    image: "redis:alpine"
    volumes:
      - /Users/tailtq/Code/databases/redis:/data
    ports:
      - 6378:6379
  mongodb:
    image: "mongo"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - /Users/tailtq/Code/databases/mongodb:/data/db
    ports:
      - 27017:27017
