# need Redis + Mongodb + containerize source + bot
version: "3.9"
services:
  redis:
    image: "redis:alpine"
    volumes:
      - "/Users/tailtq/Code/databases/redis:/data"
    ports:
      - "6378:6379"
